#pragma once
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_STATIC_LIGHT

#define RGBLIGHT_LIMIT_VAL 128
#define RGBLIGHT_DEFAULT_HUE 128
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_STATIC_LIGHT
#define RGBLIGHT_DEFAULT_ON false

#define DYNAMIC_KEYMAP_LAYER_COUNT 32
#define VIAL_COMBO_ENTRIES 64